### ISSUE TITLE
[BUG] Sporadic test failure in `test_plotting`, of `_tkinter.TclError` on Windows, Python 3.7 CI/CD

### ISSUE THREAD

**Issue by khrapovs** [sktime/sktime#2066]
**Describe the bug**

Some tests sometimes fail. Here are a few lines from the latest failure (https://github.com/alan-turing-institute/sktime/runs/5180703321?check_suite_focus=true)
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tkinter.Tk object .>, screenName = None, baseName = '__main__'
className = 'matplotlib', useTk = 1, sync = 0, use = None

    def __init__(self, screenName=None, baseName=None, className='Tk',
                 useTk=1, sync=0, use=None):
        """Return a new Toplevel widget on screen SCREENNAME. A new Tcl interpreter will
        be created. BASENAME will be used for the identification of the profile file (see
        readprofile).
        It is constructed from sys.argv[0] without extensions if None is given. CLASSNAME
        is the name of the widget class."""
        self.master = None
        self.children = {}
        self._tkloaded = 0
        # to avoid recursions in the getattr code in case of failure, we
        # ensure that self.tk is always _something_.
        self.tk = None
        if baseName is None:
            import os
            baseName = os.path.basename(sys.argv[0])
            baseName, ext = os.path.splitext(baseName)
            if ext not in ('.py', '.pyc'):
                baseName = baseName + ext
        interactive = 0
>       self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
E       _tkinter.TclError: invalid command name "tcl_findLibrary"

baseName   = '__main__'
className  = 'matplotlib'
ext        = '.py'
interactive = 0
os         = <module 'os' from 'C:\\Miniconda\\envs\\test\\lib\\os.py'>
screenName = None
self       = <tkinter.Tk object .>
sync       = 0
use        = None
useTk      = 1

C:\Miniconda\envs\test\lib\tkinter\__init__.py:2023: TclError
```

**To Reproduce**

Does not seem possible to reproduce.

**Expected behavior**

CI/CD pipeline passes.

**Versions**
<details>

```
from sktime import show_versions; show_versions()
System:
    python: 3.8.11 (default, Aug  6 2021, 10:28:10)  [GCC 10.3.0]
executable: /home/skhrapov/PycharmProjects/github/sktime/venv/bin/python
   machine: Linux-5.13.0-28-generic-x86_64-with-glibc2.33
Python dependencies:
          pip: 22.0.3
   setuptools: 53.0.0
      sklearn: 0.24.2
       sktime: 0.10.0
  statsmodels: 0.12.1
        numpy: 1.21.5
        scipy: 1.7.3
       pandas: 1.1.5
   matplotlib: 3.5.0
       joblib: 1.1.0
        numba: 0.53.0
     pmdarima: 1.8.4
      tsfresh: 0.18.0
```
</details>
