### ISSUE TITLE
[BUG] `UnboundLocalError` when trying to load regression data with timestamps

### ISSUE THREAD

**Issue by achieveordie** [sktime/sktime#3521]
**Describe the bug**

There is a bug in the logic of the loader, first found [here](https://github.com/sktime/sktime/pull/3436#issuecomment-1255933027). Essentially, one would get a `UnboundLocalError` if they try to load regression data with timestamps. This is due to imperfect loading logic in `_data_io.py`.

**To Reproduce**

Assuming there's a `AppliancesEnergy.ts`(a regression data with timestamps, available [here](https://zenodo.org/record/3902637#.YzlFp3ZBxEY)) in the same level as the code below

```python
from sktime.datasets import load_from_tsfile


if __name__ == "__main__":
    file_location = "AppliancesEnergy.ts"

    X, y = load_from_tsfile(file_location)
    print(X)
    print("----"*25)
    print(y)
```

The output of above:
``` python
Traceback (most recent call last):
  File "temp_bug_test.py", line 7, in <module>
    X, y = load_from_tsfile(file_location)
  File "D:\Projects\sktime\sktime\sktime\datasets\_data_io.py", line 383, in load_from_tsfile
    X, y = load_from_tsfile_to_dataframe(
  File "D:\Projects\sktime\sktime\sktime\datasets\_data_io.py", line 618, in load_from_tsfile_to_dataframe
    if class_val not in class_label_list:
UnboundLocalError: local variable 'class_label_list' referenced before assignment
```
**Expected behavior**

The code should produce X and y.

**Additional context**

The problem is due to the fact that there's a `class_label_list` that is to be built when metadata is read. For classification datasets with timestamps, all possible values of labels are provided with `@classlabel`. Of course, that's not possible for regression data. Therefore this list is never built.

Possible solutions:
1. (Easy Method): Add a boolean variable which is `True` for regression data (easy to know depending if `@classlabel` is found or `@targetlabel` is found). If this variable is true, then the concerned `if` statement is skipped.
2. (Correct Method?): Re-evaluate the logic of how data is being loaded, possibly restructure the code and related assumptions. Possibly plenty of work.

**Versions**
<details>

```
System:
    python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:00) [MSC v.1929 64 bit (AMD64)]
executable: D:\Anaconda\envs\sktime-dev\python.exe
   machine: Windows-10-10.0.22000-SP0

Python dependencies:
          pip: 22.2.2
   setuptools: 59.8.0
      sklearn: 1.1.2
       sktime: 0.13.4
  statsmodels: 0.13.2
        numpy: 1.22.4
        scipy: 1.8.1
       pandas: 1.4.4
   matplotlib: 3.5.3
       joblib: 1.1.0
        numba: 0.56.2
     pmdarima: 1.8.5
      tsfresh: 0.19.0
```
</details>
