### ISSUE TITLE
[BUG] Imputer fails when `missing_values` and `method="drift"` are set

### ISSUE THREAD

**Issue by AnHo4ng** [sktime/sktime#3655]
**Describe the bug**

Imputation method fails when `missing_values=[np.inf]` and `method="drift"` is set. 

**To Reproduce**

```python
from sktime.datasets import load_airline
from sktime.transformations.series.impute import Imputer
import numpy as np

# create timeseries with inf
y = load_airline()
y.iloc[3] = np.inf

# try to impute inf
Imputer(missing_values=[np.inf], method="drift").fit_transform(y)
```

**Expected behavior**

Imputer should work without errors

**Additional context**

**Versions**
<details>

```
System:
    python: 3.8.13 (default, Aug 11 2022, 15:40:13)  [Clang 13.0.0 (clang-1300.0.29.30)]
    machine: macOS-12.5.1-x86_64-i386-64bit

Python dependencies:
          pip: 22.3
   setuptools: 59.8.0
      sklearn: 1.1.2
       sktime: 0.13.4
  statsmodels: 0.13.2
        numpy: 1.22.4
        scipy: 1.8.1
       pandas: 1.4.4
   matplotlib: 3.6.1
       joblib: 1.2.0
        numba: 0.56.2
     pmdarima: 1.8.5
      tsfresh: 0.19.0
```

</details>
