### ISSUE TITLE
[BUG] Initializing any DL estimator with non-default values constructs these values only superficially

### ISSUE THREAD

**Issue by achieveordie** [sktime/sktime#4067]
**Describe the bug**

A logical bug is present in all DL estimators and is caused by not passing custom parameters to its underlying `Network` since `Network` actually makes use of these values to create the DL model of appropriate size. Take a look at the example provided below.

**To Reproduce**

```python
from pprint import pprint
from classification.deep_learning import CNNClassifier

model = CNNClassifier(
    kernel_size=3,
    n_conv_layers=1,
)

# model.summary() fails due to self.history being None, another bug

pprint(vars(model))
print("=="*25)
pprint(vars(model._network))
```

Output:
``` python
{'_X_metadata': [],
 '_class_dictionary': {},
 '_estimator_type': 'classifier',
 '_is_fitted': False,
 '_network': CNNNetwork(),
 '_tags_dynamic': {},
 '_threads_to_use': 1,
 'activation': 'sigmoid',
 'avg_pool_size': 3,
 'batch_size': 16,
 'callbacks': None,
 'classes_': [],
 'fit_time_': 0,
 'history': None,
 'kernel_size': 3,
 'loss': 'mean_squared_error',
 'metrics': None,
 'model_': None,
 'n_classes_': 0,
 'n_conv_layers': 1,
 'n_epochs': 2000,
 'optimizer': None,
 'random_state': None,
 'use_bias': True,
 'verbose': False}
==================================================
{'_tags_dynamic': {},
 'activation': 'sigmoid',
 'avg_pool_size': 3,
 'filter_sizes': [6, 12],
 'kernel_size': 7,
 'n_conv_layers': 2,
 'random_state': 0}
```

**Expected behavior**

This is happening because of `self._network = CNNNetwork()` (or corresponding Network) in the constructor of the estimator. The values that we receive are to be passed into the Network.

**Additional context**

I'm speculating this is the reason why the checks at #4036 are failing despite having very small hyperparameters. In any case, I'll open a PR to resolve this bug.

**Versions**
<details>

```
D:\Anaconda\envs\sktime-dev\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

System:
    python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:00) [MSC v.1929 64 bit (AMD64)]
executable: D:\Anaconda\envs\sktime-dev\python.exe
   machine: Windows-10-10.0.22621-SP0

Python dependencies:
          pip: 22.3.1
   setuptools: 65.5.1
      sklearn: 1.1.3
       sktime: 0.15.0
  statsmodels: 0.13.5
        numpy: 1.22.4
        scipy: 1.9.3
       pandas: 1.5.1
   matplotlib: 3.6.2
       joblib: 1.2.0
        numba: 0.56.4
     pmdarima: 2.0.1
      tsfresh: 0.19.0
```
</details>
