### ISSUE TITLE
[BUG] Callbacks cause DL estimators to fail

### ISSUE THREAD

**Issue by aaronrmm** [sktime/sktime#4088]
**Describe the bug**
Constructing a CNNClassifier with callbacks causes an error during training because the self.callbacks is never assigned to self._callbacks if self.callbacks is not None
Error:
`AttributeError: 'CNNClassifier' object has no attribute '_callbacks'`
problem area: https://github.com/sktime/sktime/blob/8fe509628405eaeaa6cbc26351e946c4a8a54687/sktime/classification/deep_learning/cnn.py#L187

**To Reproduce**
```python
import numpy as np
from sktime.classification.deep_learning import CNNClassifier

model = CNNClassifier(callbacks=[])
X_train = np.array(np.random.random((100, 1000)), dtype=np.float64)
y_train = np.array(np.random.randint(0, 2, size=(100,)), dtype=np.float64)
model.fit(X_train, y_train)
```

**Expected behavior**
self.classifier should be assigned to self._classifier OR self.classifier is what should be accessed on line 187

**Versions**
sktime==0.15.0
Please run the following code snippet and paste the output here:
 
from sktime import show_versions; show_versions()
```
System:
    python: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0]
executable: /usr/bin/python3
   machine: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29

Python dependencies:
               pip: 22.3.1
   setuptools: 65.5.1
         sklearn: 1.2.0
          sktime: 0.15.0
 statsmodels: 0.13.5
         numpy: 1.23.5
            scipy: 1.9.3
         pandas: 1.5.2
    matplotlib: 3.6.2
           joblib: 1.2.0
         numba: 0.56.4
    pmdarima: 2.0.2
          tsfresh: 0.19.0
None
```
