### ISSUE TITLE
[BUG] `temporal_train_test_split` - docstring is unclear, use with series with `pd.Multiindex` breaks

### ISSUE THREAD

**Issue by romanlutz** [sktime/sktime#4154]
**Describe the bug**

The temporal_train_test_split fails with MultiIndex. Error:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "...\Anaconda3\envs\sktime\lib\site-packages\sktime\forecasting\model_selection\_split.py", line 1428, in temporal_train_test_split
    y_train = y.groupby(yi_grp, as_index=False).nth(p1)
  File "...\Anaconda3\envs\sktime\lib\site-packages\pandas\core\series.py", line 2076, in groupby
    return SeriesGroupBy(
  File "...\Anaconda3\envs\sktime\lib\site-packages\pandas\core\groupby\groupby.py", line 949, in __init__
    raise TypeError("as_index=False only valid with DataFrame")
TypeError: as_index=False only valid with D
```

**To Reproduce**

```python
from sktime.forecasting.model_selection import temporal_train_test_split
import pandas as pd
import json
time_column_name = "WeekStarting"
time_series_id_column_names = ["Store", "Brand"]
dataset_location = "https://raw.githubusercontent.com/Azure/azureml-examples/2fe81643865e1f4591e7734bd1a729093cafb826/v1/python-sdk/tutorials/automl-with-azureml/forecasting-orange-juice-sales/dominicks_OJ.csv"
data = pd.read_csv(dataset_location, parse_dates=[time_column_name])

# Drop the columns 'logQuantity' as it is a leaky feature.
data.drop("logQuantity", axis=1, inplace=True)

data.set_index(time_series_id_column_names + [time_column_name], inplace=True)
data.sort_index(inplace=True, ascending=[True, True, True])
target_column_name = "Quantity"

y = data[target_column_name]
X = data.drop(columns=[target_column_name])
y_train, y_test, X_train, X_test = \
    temporal_train_test_split(
        y=y,
        X=X,
        test_size=20)
```

**Expected behavior**
The temporal train test split works and I get the expected return values y_train, y_test, X_train, X_test.

**Additional context**
As you can tell there's a multi index with two time series identifying columns "Store" and "Brand", and the third index column is a time column called "WeekStarting". Somehow, the sktime [code](https://github.com/sktime/sktime/blob/23d0752b8cad9d4ecc639f45fdf40f3e75961e3d/sktime/forecasting/model_selection/_split.py#L1428) has `as_index=False` which is not compatible with `pandas.Series`, but how would `y` ever not be a `Series`? That's the part I don't quite get.... Thanks in advance for your help!

**Versions**
<details>

```
System:
    python: 3.8.16 (default, Jan 17 2023, 22:25:28) [MSC v.1916 64 bit (AMD64)]
executable: ...\Anaconda3\envs\sktime\python.exe
   machine: Windows-10-10.0.19044-SP0

Python dependencies:
          pip: 22.3.1
   setuptools: 65.6.3
      sklearn: 1.0.2
       sktime: 0.15.1
  statsmodels: 0.13.5
        numpy: 1.23.5
        scipy: 1.10.0
       pandas: 1.5.3
   matplotlib: None
       joblib: 1.2.0
        numba: 0.53.1
     pmdarima: 2.0.2
      tsfresh: None
```

</details>
