### ISSUE TITLE
[BUG] dynamic time warping classifier uses euclidean distance squared, but this is not documented properly

### ISSUE THREAD

**Issue by namiyousef** [sktime/sktime#4186]
# Dynamic Time Warping uses Euclidean Distance Squared as metric

When DTW cost matrix is calculated, there is a missing square root after calculating the total sum:

```python
for i in range(x_size):
        for j in range(y_size):
            if np.isfinite(bounding_matrix[i, j]):
                sum = 0
                for k in range(dimensions):
                    sum += (x[k][i] - y[k][j]) ** 2

                cost_matrix[i + 1, j + 1] = sum  # bug
                cost_matrix[i + 1, j + 1] += min(
                    cost_matrix[i, j + 1], cost_matrix[i + 1, j], cost_matrix[i, j]
                )

return cost_matrix[1:, 1:]
```

Line  https://github.com/sktime/sktime/blob/main/sktime/distances/_dtw.py#L241 should read:
```python
cost_matrix[i + 1, j + 1] = sum ** 0.5
```

# Versions
```
System:
    python: 3.8.10 (v3.8.10:3d8993a744, May  3 2021, 09:09:08)  [Clang 12.0.5 (clang-1205.0.22.9)]
executable: /Users/YNI02/Desktop/offline_repos/correlation_engine/venv_dtw/bin/python
   machine: macOS-12.6.2-x86_64-i386-64bit

Python dependencies:
          pip: 21.1.1
   setuptools: 56.0.0
      sklearn: 1.2.1
       sktime: 0.16.0
  statsmodels: None
        numpy: 1.23.5
        scipy: 1.10.0
       pandas: 1.5.3
   matplotlib: 3.6.3
       joblib: 1.2.0
        numba: 0.56.4
     pmdarima: None
      tsfresh: None
```

# Additional Context
- Technically this doesn't have to be a bug since the squared euclidean distance is also valid, however it is unclear in the documentation that this is the case, and the results from `sktime` differ from other dtw libraries such as `dtw-python`
- Is there a reason why there is a for loop for calculating the euclidean distance? Not sure why vectorisation isn't used.
