### ISSUE TITLE
[BUG] `NaiveForecaster` fails when equally spaced list of integers is passed as forecast horizon with datasets created by `_make_series`

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#4462]
**Describe the bug**

If `NaiveForecaster` model is used to fit datasets created by `_make_series`, and then prediction is requested for a list of equally spaced integers, the prediction fails complaining of frequency mismatch.

**To Reproduce**

```python3
from sktime.utils._testing.series import _make_series
y = _make_series(n_columns=1)

from sktime.forecasting.naive import NaiveForecaster
naive = NaiveForecaster()
naive.fit(y)

naive.predict([1, 3, 5])
```

This fails with the following:

> ValueError: Frequencies from two sources do not coincide: Current: <2 * Days>, from update: <Day>.

**Expected behavior**

No error, and get a DataFrame of 3 rows.

**Additional context**

Few observations:

1. `[1, 3, 5, 6]` would work fine, but `[1, 3, 5, 7]` will fail similarly. So, this seems to be the problem with equally spaced horizons only.
2. This can possibly be more general than just `NaiveForecaster`. Same behaviour is spotted with `ARIMA` and `ThetaForecaster` as well.
3. This may be more general than "datasets created with `_make_series`", or may be even more specific. While it fails for `_make_series(n_columns=1)` or `_make_series(n_columns=2)`, it works for `load_airline()` or `load_longley()`.

**Versions**
<details>

```
System:
    python: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0]
executable: /home/conda-environments/sktime/bin/python
   machine: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.17

Python dependencies:
          pip: 23.0.1
       sktime: 0.17.1
      sklearn: 1.2.2
        numpy: 1.23.5
        scipy: 1.10.1
       pandas: 1.5.3
   matplotlib: 3.7.1
       joblib: 1.2.0
  statsmodels: 0.13.5
        numba: 0.56.4
     pmdarima: 2.0.3
      tsfresh: 0.20.0
   tensorflow: 2.12.0
tensorflow_probability: 0.19.0
```

</details>
