### ISSUE TITLE
[BUG] `PerformanceWarning` of with `ReconcilerForecaster` on 3+ hierarchical df

### ISSUE THREAD

**Issue by marrov** [sktime/sktime#4549]
**Describe the bug**
I have found that running a `ReconcilerForecaster` on a hierarchical dataset with more than three different hierarchy levels triggeres the following `PerformanceWarning`:
```
[python3.8/site-packages/sktime/transformations/hierarchical/reconcile.py:295](https://file+.vscode-resource.vscode-cdn.net/usr/local/Caskroom/miniforge/base/envs/dbconnect/lib/python3.8/site-packages/sktime/transformations/hierarchical/reconcile.py:295): PerformanceWarning: indexing past lexsort depth may impact performance.
  s_matrix.loc[tuple(agg_ind[::-1]), i] = 1.0
```

**To Reproduce**
```python
from sktime.forecasting.reconcile import ReconcilerForecaster
from sktime.forecasting.naive import NaiveForecaster
from sktime.utils._testing.hierarchical import _bottom_hier_datagen

small_y = _bottom_hier_datagen(no_levels=2, no_bottom_nodes=10)
big_y = _bottom_hier_datagen(no_levels=3, no_bottom_nodes=10)

naive_w_reconciler = ReconcilerForecaster(NaiveForecaster(), method="bu")

naive_w_reconciler.clone().fit_predict(small_y, fh=[1]) # No warning, all ok
naive_w_reconciler.clone().fit_predict(big_y, fh=[1]) # PerformanceWarning!
```

**Expected behavior**
The `fit_predict()` method of a `ReconcilerForecaster` should not produce a `PerformanceWarning`, regardless of the size of the hierarchy.

**Additional context**
The warning is triggered by this [line in the source code](https://github.com/sktime/sktime/blob/d85102ffd10f6531316015a1ac6c80c0b1687801/sktime/transformations/hierarchical/reconcile.py#L295). I checked and this happens when the index is not sorted and causes performance issues (see [this related stackoverflow question](https://stackoverflow.com/questions/54307300/what-causes-indexing-past-lexsort-depth-warning-in-pandas)). Maybe the "unordered" index is somehow a requirement for the reconciler, but it seems it could potentially be an easy fix.

@fkiraly suggested me to tag @ciaran-g and @VyomkeshVyas on this issue.

**Versions**
<details>

```
System:
    python: 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:05:36)  [Clang 14.0.6 ]
executable: [/usr/local/Caskroom/miniforge/base/envs/sktime/bin/python](https://file+.vscode-resource.vscode-cdn.net/usr/local/Caskroom/miniforge/base/envs/sktime/bin/python)
   machine: macOS-10.16-x86_64-i386-64bit

Python dependencies:
          pip: 23.1.2
       sktime: 0.17.2
      sklearn: 1.2.2
        numpy: 1.23.5
        scipy: 1.10.1
       pandas: 1.5.3
   matplotlib: 3.7.1
       joblib: 1.2.0
  statsmodels: 0.13.5
        numba: 0.56.4
     pmdarima: None
      tsfresh: None
   tensorflow: None
tensorflow_probability: None
```

</details>
