### ISSUE TITLE
[BUG] ReconcilerForecaster in a pipeline fails (inverse_transform tripped up by __total?)

### ISSUE THREAD

**Issue by davidgilbertson** [sktime/sktime#4750]
**Describe the bug**

I want to use the `ReconcilerForecaster`, but I also want a pipeline that does some transforms (and their inverses). When I try to run the code below I get the error:

```txt
RuntimeError: found different number of instances in transform than in fit. number of instances seen in fit: 8; number of instances seen in transform: 11
```

I'm new to `sktime` but I believe the extra instances are coming from new `__total` nodes.

It's quite possible that I'm just doing something dumb, I haven't read through all the docs yet.

**To Reproduce**

```python
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.forecasting.naive import NaiveForecaster
from sktime.forecasting.reconcile import ReconcilerForecaster
from sktime.pipeline import make_pipeline
from sktime.transformations.series.boxcox import BoxCoxTransformer
from sktime.utils._testing.hierarchical import _make_hierarchical

y = _make_hierarchical()
y_trn, y_tst = temporal_train_test_split(y, test_size=5)

forecaster = make_pipeline(
    BoxCoxTransformer(),
    ReconcilerForecaster(NaiveForecaster()),
)

forecaster.fit(y_trn)

preds = forecaster.predict(fh=[1, 2, 3])

```

**Expected behavior**

Not sure what I'd expect exactly, that the inverse (post-pred) pass would do `drop("__total", errors="ignore")` or something.

**Additional context**

**Versions**
<details>

```
System:
    python: 3.10.8 (main, Oct 12 2022, 19:14:26) [GCC 9.4.0]
executable: /home/davidg/.virtualenvs/learning/bin/python
   machine: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python dependencies:
          pip: 23.1.2
       sktime: 0.19.1
      sklearn: 1.2.2
        numpy: 1.24.3
        scipy: 1.10.1
       pandas: 2.0.1
   matplotlib: 3.7.0
       joblib: 1.2.0
  statsmodels: 0.13.5
        numba: None
     pmdarima: 2.0.3
      tsfresh: None
   tensorflow: None
tensorflow_probability: None
```
</details>
