### ISSUE TITLE
[BUG] Allowing Delegators to work with estimators that don't support native methods like `get_fitted_params()`

### ISSUE THREAD

**Issue by achieveordie** [sktime/sktime#4966]
**Describe the bug**

I found this issue while diagnosing check fails in #4596. 

Consider the scenario of adapting sklearn's `GridSearchCV` for time series classification via `_DelegatedClassifier` as `TSCGridSearchCV` (consistent with what we're trying to do in #4596). Any instance of `TSCGridSearchCV` should support methods like `get_fitted_params()`.

In the current implementation, `_DelegatedClassifier` (and sister delegators like `_DelegatedRegressor`) calls the underlying estimator's `get_fitted_params()` which works fine if the delegated class contains this method (all sktime-native entities), but in the case it belongs to a 3rd-party package like sklearn, it will result in an `AttributeError`.

**To Reproduce**

The following piece of code should make it clearer: 

```python
from sktime.classification.distance_based import ShapeDTW
from sktime.classification.model_selection import TSCGridSearchCV
from sktime.datasets import load_gunpoint

shape_dtw_est = ShapeDTW()
param_grid = {
    "n_neighbors": [1, 5, 10],
    "subsequence_length": [15, 30]
}

grid_search = TSCGridSearchCV(estimator=shape_dtw_est, param_grid=param_grid)

X, y = load_gunpoint(split="train", return_X_y=True, return_type="numpy3D")
grid_search.fit(X, y)

print(grid_search.get_fitted_params())
```

Output:
``` python
Traceback (most recent call last):
  File "...temp-tuning.py", line 16, in <module>
    print(grid_search.get_fitted_params())
  File "...sktime\base\_base.py", line 423, in get_fitted_params
    fitted_params = self._get_fitted_params()
  File "...sktime\sktime\classification\_delegate.py", line 143, in _get_fitted_params
    return estimator.get_fitted_params()
AttributeError: 'GridSearchCV' object has no attribute 'get_fitted_params'
```
The delegated estimator in this case is sklearn's [`GridSearchCV`](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/model_selection/_search.py#L1059).

**Possible Solutions**

The direct way to solve conditions like this would be to create `_get_fitted_params()` to be context-aware. In the scenario where delegated estimators are not `sktime`-native, we track the list of attributes we want to be represented via `get_fitted_params()` from the delegated estimator and simply use this list in conjugation with `getattr()` to build the dictionary.

**Additional context**

I'm also interested in knowing other possible solutions that are easier / more suited than my recommendation above.

**Versions**
<details>

```
System:
    python: 3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\sagar\miniconda3\envs\sktime-dev\python.exe
   machine: Windows-10-10.0.22621-SP0

Python dependencies:
          pip: 23.1.2
       sktime: 0.18.0
      sklearn: 1.2.2
        numpy: 1.24.3
        scipy: 1.10.1
       pandas: 2.0.3
   matplotlib: 3.7.2
       joblib: 1.3.1
  statsmodels: 0.14.0
        numba: 0.57.1
     pmdarima: 2.0.3
      tsfresh: 0.20.1
   tensorflow: 2.13.0
tensorflow_probability: None
```
</details>
