### ISSUE TITLE
[BUG] RocketClassifier SystemError: _PyEval_EvalFrameDefault

### ISSUE THREAD

**Issue by ericleonardo** [sktime/sktime#5000]
Please, how to fix this error when Training RocketClassifier on 3d data?
When I run the basic example from Docs, it works perfectly.
But just change data to 3d numpy array and error comes not allowing train.
3d data in shape [n_instances, n_dimensions, series_length] as specified in the Docs.
X_train data shape: (2618, 2, 3) (2618 samples, 2 features, 3 lookback length). Thank you!

```python
from sktime.classification.kernel_based import RocketClassifier

clf = RocketClassifier(num_kernels=500, rocket_transform='multirocket', use_multivariate='yes', n_jobs=-1)
clf.fit(X_train, y_train)
```

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
AssertionError: Sizes of $372binary_subscr.15, $390binary_subscr.26 do not match on /usr/local/lib/python3.10/dist-packages/sktime/transformations/panel/rocket/_multirocket_multi_numba.py (736)

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
[<ipython-input-50-bed19c0333df>](https://localhost:8080/#) in <cell line: 1>()
----> 1 clf.fit(rolling_X_train, y_train_seq)

9 frames
[/usr/local/lib/python3.10/dist-packages/sktime/transformations/panel/rocket/_multirocket_multivariate.py](https://localhost:8080/#) in _transform(self, X, y)
    171         set_num_threads(n_jobs)
    172 
--> 173         X = _transform(
    174             X,
    175             _X1,

SystemError: _PyEval_EvalFrameDefault returned a result with an exception set
```

**Comment by fkiraly** [comment]
Well, that looks weird. Looks like some `numba` failure?

May I ask for diagnosis:

* can you generate the error with `sktime` dummy data or random numpy arrays? Or is it only happening for your data?
* can you please report your package versions, following the instructions in the bug reporting issue template?

**Comment by ericleonardo** [comment]
Hi! Running basic example from Docs with dummy data works perfectly. Error only occurs with my data.
I'm using Colab with local host (Docker) on windows.

```
System:
    python: 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]
executable: /usr/bin/python3
   machine: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31

Python dependencies:
          pip: 23.1.2
       sktime: 0.21.0
      sklearn: 1.2.2
       skbase: 0.4.6
        numpy: 1.22.4
        scipy: 1.10.1
       pandas: 1.5.3
   matplotlib: 3.7.1
       joblib: 1.2.0
  statsmodels: 0.13.5
        numba: 0.56.4
     pmdarima: 2.0.3
      tsfresh: 0.20.1
   tensorflow: 2.12.0
tensorflow_probability: 0.20.0
```

**Comment by fkiraly** [comment]
Thanks!

> Error only occurs with my data.

Well, that's odd.
If you can't share your data, could you share the output of the following?

```python
print(type(X_train))
print(X_train.dtype)
print(X_train.shape)
```

**Comment by ericleonardo** [comment]
Yes, I can share my numpy data.. please, see attached.
3d data in shape [n_instances, n_dimensions, series_length] as said in Docs.

print(type(X_train))
print(X_train.dtype)
print(X_train.shape)

```
<class 'numpy.ndarray'>
float64
(23574, 2, 3)
```

Error occurs after 2 minutes of training. Not in right start button click (Colab).
Now I tried Colab from Google remote environment (not local host) and same error.

```
from sktime.classification.kernel_based import RocketClassifier
clf = RocketClassifier(num_kernels=500, rocket_transform='multirocket', use_multivariate='yes', n_jobs=-1)
clf.fit(X_train, Y_train)
```
[Xtrain_Ytrain.zip](https://github.com/sktime/sktime/files/12233533/Xtrain_Ytrain.zip)

**Comment by fkiraly** [comment]
can you check:

* is any entry `nan` or infinite?
* if you generate a random `numpy` array of same size and pass it, do you still get the error?

**Comment by fkiraly** [comment]
I have reproduced the error using the exact data, on windows, python 3.11, numba 0.57.1.

Versions:

```
System:
    python: 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)]
executable: [c:\ProgramData\Anaconda3\envs\sktime-skbase-numba-311\python.exe](file:///C:/ProgramData/Anaconda3/envs/sktime-skbase-numba-311/python.exe)
   machine: Windows-10-10.0.22621-SP0

Python dependencies:
          pip: 23.2.1
       sktime: 0.21.0
      sklearn: 1.3.0
       skbase: 0.4.6
        numpy: 1.24.4
        scipy: 1.11.1
       pandas: 2.0.3
   matplotlib: None
       joblib: 1.3.1
  statsmodels: None
        numba: 0.57.1
     pmdarima: None
      tsfresh: None
   tensorflow: None
tensorflow_probability: None
```

Useful code to load the files:

```python
import numpy as np

PATH = "npy_files_are_here"

X_train = np.load(PATH + "X_train.npy")
y_train = np.load(PATH + "y_train.npy")
```
