### ISSUE TITLE
[BUG] pmdarima dependency requirement should be increased

### ISSUE THREAD

**Issue by romanlutz** [sktime/sktime#5081]
**Describe the bug**

I installed sktime==0.21.0, scikit-learn==1.3.0 and pmdarima==1.8.0 but I'm hitting the following error when importing pmdarima

```
----> 1 import pmdarima

File C:\ProgramData\Anaconda3\envs\raitoolboxdev\lib\site-packages\pmdarima\__init__.py:51
     48 from . import __check_build
     50 # Stuff we want at top-level
---> 51 from .arima import auto_arima, ARIMA, AutoARIMA, StepwiseContext, decompose
     52 from .utils import acf, autocorr_plot, c, pacf, plot_acf, plot_pacf, \
     53     tsdisplay
     54 from .utils._show_versions import show_versions

File C:\ProgramData\Anaconda3\envs\raitoolboxdev\lib\site-packages\pmdarima\arima\__init__.py:6
      1 # -*- coding: utf-8 -*-
      2 #
      3 # Author: Taylor Smith <taylor.smith@alkaline-ml.com>
      5 from .approx import *
----> 6 from .arima import *
      7 from .auto import *
      8 from .utils import *

File C:\ProgramData\Anaconda3\envs\raitoolboxdev\lib\site-packages\pmdarima\arima\arima.py:8
      1 # -*- coding: utf-8 -*-
      2 #
      3 # Author: Taylor Smith <taylor.smith@alkaline-ml.com>
      4 #
      5 # A user-friendly wrapper to the statsmodels ARIMA that mimics the familiar
      6 # sklearn interface.
----> 8 from sklearn.utils.metaestimators import if_delegate_has_method
      9 from sklearn.utils.validation import check_array
     11 from statsmodels import api as sm

ImportError: cannot import name 'if_delegate_has_method' from 'sklearn.utils.metaestimators' (C:\ProgramData\Anaconda3\envs\raitoolboxdev\lib\site-packages\sklearn\utils\metaestimators.py)
```

**To Reproduce**

```python
import pmdarima
```
or train a model with `sktime.forecasting.arima.AutoARIMA`, but this is the fastest way to reproduce the problem.

**Expected behavior**

No error 🙂 
I have read #1503 and #4585, of course, but it seems like the minimum version for pmdarima needs to be increased from 1.8.0 to something higher that is compatible with scikit-learn to avoid this bug.

**Additional context**

**Versions**
 sktime==0.21.0, scikit-learn==1.3.0 and pmdarima==1.8.0

```
System:
    python: 3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]
executable: C:\ProgramData\Anaconda3\envs\raitoolboxdev\python.exe
   machine: Windows-10-10.0.19045-SP0

Python dependencies:
          pip: 23.2.1
       sktime: 0.21.0
      sklearn: 1.3.0
       skbase: 0.4.6
        numpy: 1.22.3
        scipy: 1.5.3
       pandas: 1.1.5
   matplotlib: None
       joblib: 1.2.0
  statsmodels: 0.11.1
        numba: 0.55.2
     pmdarima: None
      tsfresh: None
   tensorflow: None
tensorflow_probability: None
```

</details>
