### ISSUE TITLE
[MNT] split optional dependencies and CI testing per components

### ISSUE THREAD

**Issue by yarnabrina** [sktime/sktime#5101]
I want to suggest a continuation from the recent introduction of CI testing only per module.

As of now, `sktime` offers only one optional dependencies: `all_extras`, which is massive and definitely has some packages which have overlapping (if not conflicting) dependencies. My suggestion is to introduce few more optional dependencies, one per each component:

1. forecasting
2. classification
3. transformation
4. regression
5. clustering
6. etc.

What `pip install sktime[forecasting]` will do is install `sktime` and all soft dependencies by all forecasters in `sktime`, and similarly for other components.

There can be further classifications, for example `forecasting-dl` vs `forecasting-non-dl` can be one split, as deep learning packages (e.g. `torch`) often have serious system dependencies which may not be always possible to be used by all users in all environments.

After addition of these, I want to propose to split the CI test job into component wise parts. For example, instead of using one single job on `python 3.9` and `macos`, we can have multiple, one for each component. Each of this component runs only if change is detected in that directory or in `base` (Github Actions support this natively) and if selected, runs the tests on modified modules in that component after only installing the relevant sub-dependencies.

Proposed tasks

- [x] optional dependency specification in `pyproject.toml` per component
- [x] CI job split per component
- [x] CI job condition change per component
- [x] new CI job to be run manually before each release (or as required) for testing all components

Inviting @fkiraly, @benHeid, @achieveordie to consider this suggestion and share feedbacks.

**Comment by fkiraly** [comment]
* agreed on dependency specifications, that might make it easier for users to get what they want
    * although I'm not sure about separating transformations. There are some dependencies there which seem more specific to one or the other learning task, such as `holidays` being specific to forecasting.
* re splitting up CI elements, is that really necessary now that we have incremental testing? I think we'll get down to below 10 minutes with the decorators for non-suite tests without problems. Given this, what is the benefit from splitting the CI?
    * it will have no effect on the `TestAll` tests anymore, as long as only one estimator is changed
    * it will have no effect on non-suite tests that are decorated with `run_test_for_class`, which in the optimal end state are all estimator specific ones
    * and the remaining tests are of a kind that I would always execute, as they cover the framework (even if it is specific to an estimator type)

**Comment by yarnabrina** [comment]
> re splitting up CI elements, is that really necessary now that we have incremental testing? I think we'll get down to below 10 minutes with the decorators for non-suite tests without problems. Given this, what is the benefit from splitting the CI?

Let's consider a case: I (any contributor) create a PR modifying `AutoARIMA` forecaster.

If I am not wrong, the way it currently works is `pytest` first lists all tests across all components, which is ~77K tests and it takes takes about 1 minute. The numbers are based on my local setup. Then it goes over all of these, decides whether to run it or not, and then goes over the remaining to decide whether to run in this job or something else.

I think this is not required, as I (the contributor) and reviewers will know that it is enough to look between only forecasting modules. It'll be much smaller list to loop through just `sktime/forecasting` instead of full `sktime`. Also, if something fails unexpectedly on a full CI run on `main`, browsing traceback corresponding the failed test in the huge test log seems really difficult to me.

So, the way I see it, it'll help us to have logically similar smaller groups of tests, and easy to debug. Also, I don't know how coverage gets combined from multiple jobs currently, but this will allow us to report coverage per component as well.

(To be honest, my suggestion was really based on unnecessary search over all components and smaller logical grouping. Coverage seemed like a nice possible side effect now, didn't think of it earlier.)

---

Even if you don't agree about 2nd or 3rd tasks, I think the 4th task (manually triggerable CI job to run all tests) is still relevant? Or, do we have a way to test this now already? I remembered some CRON job discussion @hazrulakmal suggested somewhere, but don't know if it's done already or not.

**Comment by fkiraly** [comment]
> Let's consider a case

I see - I consider this a valid, and strong argument for a lookup architecture instead of the current filtering architecture. Where lookup/filtering refers to the logic to find the tests to execute.

Filtering would be: find all tests first, and then decide for each and everyone which to run. Examples are exhaustive search then filter by condition or property.

Lookup would be: determine a list of tests to run first, and then find them. Examples would be dispatch or list lookup.

Noting that the "split by module" archithecture proposed in the OP moves from the current, which is entirely filtering based, to a lookup/filtering hybrid. But, also noting, that the argument above is not specifically in favour of this solution (which I consider a bit over-complicating).

Following this line of analysis, would a pure lookup architecture not be best, hence?
The general question being, which entry points we would have to address. Is it `all_estimators` and the fixture generation in the `TestAll` classes, or is it also `pytest`'s own crawling mechanisms?

**Comment by fkiraly** [comment]
>I think the 4th task (manually triggerable CI job to run all tests) is still relevant? Or, do we have a way to test this now already? I remembered some CRON job discussion @hazrulakmal suggested somewhere, but don't know if it's done already or not.

I agree that this is desirable and we should do this.

The current solution is here: https://github.com/sktime/sktime/pull/5083 (manual trigger to run all tests), but CRON and automated seems better. I just don't know how to set it up, off the top of my head. I could probably learn it, but then it becomes a time prioritization exercise.

**Comment by yarnabrina** [comment]
I'm glad to convince you, but got a bit worried by this:

> But, also noting, that the argument above is not specifically in favour of this solution (which I consider a bit over-complicating).
> 
> Following this line of analysis, would a pure lookup architecture not be best, hence?

Just to confirm we're talking about same thing, here's what I was trying to suggest:

current case:

<details>

<summary> old-all.yml </summary>

```yml
name: test workflow
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test-job-id:
    name: test job name
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: repository checkout step
        uses: actions/checkout@v3
      - name: python environment step
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: dependencies installation step
        run: python3 -m pip install .[all_extras]
      - name: unit test step
        run: python3 -m pytest
      - name: test coverage step
        uses: codecov/codecov-action@v3
```

</details>

proposed case:

<details>

<summary> new-all.yml </summary>

```yml
name: all test workflow
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
jobs:
  all-test-job-id:
    name: all test job name
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: repository checkout step
        uses: actions/checkout@v3
      - name: python environment step
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: dependencies installation step
        run: python3 -m pip install .[all_extras]
      - name: unit test step
        run: python3 -m pytest sktime
      - name: test coverage step
        uses: codecov/codecov-action@v3
```

</details>

<details>

<summary> new-base.yml </summary>

```yml
name: base test workflow
on:
  pull_request:
    branches:
      - main
    paths:
      - sktime/base
  push:
    branches:
      - main
    paths:
      - sktime/base
jobs:
  base-test-job-id:
    name: base test job name
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: repository checkout step
        uses: actions/checkout@v3
      - name: python environment step
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: dependencies installation step
        run: python3 -m pip install .
      - name: unit test step
        run: python3 -m pytest sktime/base
      - name: test coverage step
        uses: codecov/codecov-action@v3
```

</details>

<details>

<summary> new-forecast.yml </summary>

```yml
name: forecast test workflow
on:
  pull_request:
    branches:
      - main
    paths:
      - sktime/foreasting
  push:
    branches:
      - main
    paths:
      - sktime/foreasting
jobs:
  foreast-test-job-id:
    name: forecast test job name
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: repository checkout step
        uses: actions/checkout@v3
      - name: python environment step
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: dependencies installation step
        run: python3 -m pip install .[forecasting]
      - name: unit test step
        run: python3 -m pytest sktime/forecasting
      - name: test coverage step
        uses: codecov/codecov-action@v3
```

</details>

etc.

> None of these workflows are tested, these are just for illustration. There are definitely lots of duplications, which hopefully can be solved with `nox` like tools in combination with published actions like `dorny/paths-filter`.

So, my idea was that for a new PR, `forecast` workflow will be triggered only if there's a change in `sktime/forecasting` sub-directory, and only tests contained in that will be executed. The non-necessary installations should also be skipped, which means that this will be tested against latest version of the packages allowed by other packages in this soft-dependency, and since it'd be a lot less than overall list of dependencies, it'll be differently and likely newer than current setup. Similarly for other components, including base framework though that can be modified as required.

And for manual/scheduled trigger of all tests, `new-all` workflow can be used. It can be triggered manually anytime manually from UI (may not be accessible to all though) and will also run every Sunday at 00:00 UTC.

Given the above, can you please elaborate on these? I didn't understand those points.

> The general question being, which entry points we would have to address. Is it all_estimators and the fixture generation in the TestAll classes, or is it also pytest's own crawling mechanisms?
