### ISSUE TITLE
[BUG] `ignores-exogeneous-X` is kept for `TransformedTargetForecaster` even if transformer would use exog

### ISSUE THREAD

**Issue by SmirnGregHM** [sktime/sktime#5518]
**Describe the bug**
`ignores-exogeneous-X` is kept for `TransformedTargetForecaster` even if transformer would use exog

I want to have a forecasting pipeline where I define part of the logic in the transformer. For example, I want to impute holidays data. Holidays mask is exogeneous. I have implemented a transformer that does the job, but it is not working because my final transformer `ignores-exogeneous-X`.

**To Reproduce**
```python
from sktime.forecasting.naive import NaiveForecaster
from sktime.transformations.series.feature_selection import FeatureSelection
from sktime.forecasting.fbprophet import Prophet

print(f"{Prophet().get_tag('ignores-exogeneous-X') = }")
print(f"{(FeatureSelection() * Prophet()).get_tag('ignores-exogeneous-X') = }")

print(f"{NaiveForecaster().get_tag('ignores-exogeneous-X') = }")
print(f"{(FeatureSelection() * NaiveForecaster()).get_tag('ignores-exogeneous-X') = }")
```

```python
Prophet().get_tag('ignores-exogeneous-X') = False
(FeatureSelection() * Prophet()).get_tag('ignores-exogeneous-X') = False
NaiveForecaster().get_tag('ignores-exogeneous-X') = True
(FeatureSelection() * NaiveForecaster()).get_tag('ignores-exogeneous-X') = True
```

**Expected behavior**
```python
Prophet().get_tag('ignores-exogeneous-X') = False
(FeatureSelection() * Prophet()).get_tag('ignores-exogeneous-X') = False
NaiveForecaster().get_tag('ignores-exogeneous-X') = True
(FeatureSelection() * NaiveForecaster()).get_tag('ignores-exogeneous-X') = **False**
```

**Versions**
```
System:
    python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:39:40) [Clang 15.0.7 ]
executable: /opt/homebrew/Caskroom/miniconda/base/envs/hcem_test/bin/python
   machine: macOS-13.2.1-x86_64-i386-64bit

Python dependencies:
          pip: 23.2.1
       sktime: 0.24.0
      sklearn: 1.3.1
       skbase: 0.5.1
        numpy: 1.25.2
        scipy: 1.11.3
       pandas: 2.1.1
   matplotlib: 3.8.0
       joblib: 1.3.2
        numba: None
  statsmodels: 0.14.0
     pmdarima: 2.0.3
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None
```
