### ISSUE TITLE
[BUG] error while fitting on `cINNForecaster`

### ISSUE THREAD

**Issue by geetu040** [sktime/sktime#6122]
**Describe the bug**

**To Reproduce**

I have taken this code from the example given in docstring of `cINNForecaster` and have tried it locally and on google colab, giving the same error.

code:
```python
# pip install sktime[dl]
from sktime.forecasting.conditional_invertible_neural_network import (
    cINNForecaster,
)
from sktime.datasets import load_airline
y = load_airline()
model = cINNForecaster() # doctest: +SKIP
model.fit(y) # doctest: +SKIP
y_pred = model.predict(fh=[1,2,3]) # doctest: +SKIP
```
error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-53f2d3cfee00> in <cell line: 8>()
      6 y = load_airline()
      7 model = cINNForecaster() # doctest: +SKIP
----> 8 model.fit(y) # doctest: +SKIP
      9 y_pred = model.predict(fh=[1,2,3]) # doctest: +SKIP

4 frames
/usr/local/lib/python3.10/dist-packages/sktime/forecasting/base/_base.py in fit(self, y, X, fh)
    385         # we call the ordinary _fit if no looping/vectorization needed
    386         if not vectorization_needed:
--> 387             self._fit(y=y_inner, X=X_inner, fh=fh)
    388         else:
    389             # otherwise we call the vectorized version of fit

/usr/local/lib/python3.10/dist-packages/sktime/forecasting/conditional_invertible_neural_network.py in _fit(self, y, fh, X)
    220             normalise_index=True,
    221         )
--> 222         self.function.fit(rolling_mean.dropna())
    223         self.fourier_features = FourierFeatures(
    224             sp_list=self._sp_list, fourier_terms_list=self._fourier_terms_list

/usr/local/lib/python3.10/dist-packages/sktime/forecasting/base/_base.py in fit(self, y, X, fh)
    385         # we call the ordinary _fit if no looping/vectorization needed
    386         if not vectorization_needed:
--> 387             self._fit(y=y_inner, X=X_inner, fh=fh)
    388         else:
    389             # otherwise we call the vectorized version of fit

/usr/local/lib/python3.10/dist-packages/sktime/forecasting/trend/_curve_fit_forecaster.py in _fit(self, y, X, fh)
    135                 x = x // self.delta_
    136 
--> 137         self.params_ = curve_fit(self.function, x, y.values, **self._curve_fit_params)
    138         return self
    139 

/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minpack_py.py in curve_fit(f, xdata, ydata, p0, sigma, absolute_sigma, check_finite, bounds, method, jac, full_output, nan_policy, **kwargs)
    899 
    900     if ydata.size == 0:
--> 901         raise ValueError("`ydata` must not be empty!")
    902 
    903     # nan handling is needed only if check_finite is False because if True,

ValueError: `ydata` must not be empty!
```

**Additional context**
Although it passes all tests on `check_estimator`

<details>

```py
from sktime.utils.estimator_checks import check_estimator
from sktime.forecasting.conditional_invertible_neural_network import cINNForecaster
results = check_estimator(cINNForecaster)
# All tests passed
```

</details>

**Versions**
<details>

```
System:
    python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
executable: /usr/bin/python3
   machine: Linux-6.1.58+-x86_64-with-glibc2.35

Python dependencies:
          pip: 23.1.2
       sktime: 0.27.0
      sklearn: 1.2.2
       skbase: 0.7.5
        numpy: 1.25.2
        scipy: 1.11.4
       pandas: 1.5.3
   matplotlib: 3.7.1
       joblib: 1.3.2
        numba: 0.58.1
  statsmodels: 0.14.1
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: 2.2.1+cu121
   tensorflow: 2.14.0
tensorflow_probability: None
```

</details>
