### ISSUE TITLE
[DOC] Building docs locally failing due to a corrupt notebook

### ISSUE THREAD

**Issue by fnhirwa** [sktime/sktime#6425]
#### Describe the issue linked to the documentation

The issue is a notebook, `examples/00_sktime_intro.ipynb` that is corrupt and causing local docs building to fail.

```
Notebook error:
JSONDecodeError in examples/00_sktime_intro.ipynb:
Expecting value: line 1 column 1 (char 0)
make: *** [html] Error 2
```
System info:
```
System:
    python: 3.9.18 (CPython, Aug 24 2023 18:16:58, Clang 15.0.0 (clang-1500.1.0.2.5))
executable: /Users/hirwa/Desktop/open/stimedev/bin/python
   machine: macOS-14.4.1-arm64-arm-64bit

Python dependencies:
          pip: 23.3.1
          sktime: 0.29.0
          sklearn: None
          skbase: None
          numpy: 1.26.4
          scipy: 1.13.0
          pandas: 2.1.4
          matplotlib: 3.8.4
          joblib: 1.4.0
          numba: 0.59.1
          statsmodels: 0.14.2
          pmdarima: 2.0.4
          statsforecast: 1.7.4
          tsfresh: 0.20.2
          tslearn: 0.6.3
          torch: 2.3.0
          tensorflow: 2.16.1
          tensorflow_probability: None
          ```
#### Suggest a potential alternative/fix
Fixing the notebook would solve the issue
