### ISSUE TITLE
[BUG] DirectReductionForecaster fails with `TypeError: Unsupported input data type in DirectReductionForecaster`

### ISSUE THREAD

**Issue by SultanOrazbayev** [sktime/sktime#6547]
Hello, I am attempting to run a simple example that uses `DirectReductionForecaster`, however it fails with `TypeError`.

From the traceback, it seems that the `pd.DataFrame` is converted to `VectorizedDF` at some point.

Reproducible example:

```python
from sklearn.linear_model import LinearRegression
from sktime.forecasting.compose import (
    DirectReductionForecaster,
)
from sktime.utils._testing.series import _make_series

df = _make_series(n_timepoints=30, n_columns=3)
x_columns = df.columns
df["y1"] = 10 + 3 * df[0]
df["y2"] = 15 + 5 * df[0]
y = df[["y1", "y2"]]
X = df[x_columns]

forecaster = DirectReductionForecaster(estimator=LinearRegression(), window_length=0)

fh = [1, 2, 3]
forecaster.fit_predict(y=y, X=X, fh=fh)
```

**Versions**
<details>

```
System:
    python: 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:38:07) [Clang 16.0.6 ]
executable: [/Users/somename/miniconda3/envs/mff-dev/bin/python](https://file+.vscode-resource.vscode-cdn.net/Users/somename/miniconda3/envs/mff-dev/bin/python)
   machine: macOS-14.5-arm64-arm-64bit

Python dependencies:
          pip: 23.3.2
       sktime: 0.30.1
      sklearn: 1.4.0
       skbase: 0.8.0
        numpy: 1.26.3
        scipy: 1.12.0
       pandas: 2.2.2
   matplotlib: 3.8.3
       joblib: 1.3.2
        numba: None
  statsmodels: 0.14.1
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None
```

</details>
