### ISSUE TITLE
[BUG] Transformations that drop/re-align `y` and `X` break reduction forecaster in `predict`.

### ISSUE THREAD

**Issue by hliebert** [sktime/sktime#6945]
**Describe the bug**

Transformer pipelines that drop observations and re-align `X` with `y` mangle inputs in combination with reducers.

I've noticed this bug while working on `DirectReductionForecaster` in #6650. The workaround was to pass `_X` instead of `X` in predict with `X_treatment="shifted"`.

However, I think this may ultimately be caused by the interface being broken elsewhere. (We have noticed previously that pipelines including transformation that drop observations tend to be fragile).

**To Reproduce**

Regrettably, this triggers another bug first (fixed in #6944), so it requires using that branch or `main` after the PR has been merged. After that, it can be triggered by setting `X_treatment="concurrent"` on `main` (or by setting `X_treatment` to either `shifted` or `concurrent` on commit `f006b315b05d7bb7636d9b04f51a08ceb380540f`).

In the example below, y is logged and differenced, and the missing observation due to differencing is dropped. X is then re-aligned to match y.

```python
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor

from sktime.datasets import load_longley
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.compose import ForecastingPipeline, TransformedTargetForecaster
from sktime.forecasting.compose._reduce import DirectReductionForecaster
from sktime.split import temporal_train_test_split
from sktime.transformations.series.boxcox import LogTransformer
from sktime.transformations.series.difference import Differencer
from sktime.transformations.series.subset import IndexSubset

y, X = load_longley()

horizon = ForecastingHorizon(np.arange(1, 3), is_relative=True)

reduction_forecaster = DirectReductionForecaster(
    RandomForestRegressor(),
    window_length=3,
    X_treatment="concurrent",
    windows_identical=False,
)

# this is needed to align X to y (differencing causes loss of first obs)
pipe_x = ForecastingPipeline(
    [
        IndexSubset(index_treatment="remove"),
        reduction_forecaster,
    ]
)

pipe = TransformedTargetForecaster(
    [
        LogTransformer(),
        Differencer(lags=1, na_handling="drop_na"),
        pipe_x,
    ]
)

y_train, y_test, X_train, X_test = temporal_train_test_split(y, X)

# This works
pipe.fit(y_train, X_train, fh=horizon)
pipe.predict(fh=horizon, X=X_test)

# This doesn't
# For `concurrent`, it is unclear to me what the exected behavior is (fail with informative message?). 
# However, the mangled data suggests this may be a more fundamental issue elsewhere.
# For `shifted`, this should not fail (regardless of whether `X` or `_X` is passed internally).
pipe.fit(y, X, fh=horizon)
pipe.predict(fh=horizon, X=X)
```

**Expected behavior**
Unclear with concurrent (fail with informative message?). No error with `shifted`.

**Versions**

```
System:
    python: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
executable: /home/hliebe/Desktop/sktime/.venv/bin/python
   machine: Linux-6.5.0-44-generic-x86_64-with-glibc2.35

Python dependencies:
          pip: 22.0.2
       sktime: 0.31.1
      sklearn: 1.5.0
       skbase: 0.8.0
        numpy: 1.26.4
        scipy: 1.13.1
       pandas: 2.2.2
   matplotlib: None
       joblib: 1.4.2
        numba: None
  statsmodels: None
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None
```
