### ISSUE TITLE
[BUG] Irregular Time Series Data Unsupported for Time Series K Means

### ISSUE THREAD

**Issue by chirag03k** [sktime/sktime#6989]
**Describe the bug**
This occurred when attempting to cluster several unequal length series. Attempting to cluster them using `TimeSeriesKMeans` results in the error `The data has unequal length series, this clusterer cannot handle unequal length series` despite the [documentation](https://www.sktime.net/en/stable/api_reference/auto_generated/sktime.clustering.k_means.TimeSeriesKMeans.html#sktime.clustering.k_means.TimeSeriesKMeans.fit) on the `fit` function explicitly declaring the that the series may be of equal or unequal length.

**To Reproduce**
```python
ts1 = pd.Series(data=[1,2,3,5,6,9], index=[0,1,2,3,4,5])
ts2 = pd.Series(data=[1,2,6,3,6,1,3,0,3,4,3], index=[0,1,3,5,8,7,10,12,15,19,21])
ts3 = pd.Series(data=[1,5,6], index=[0,2,5])
data_df = pd.DataFrame()
data_df["Series"] = [ts1, ts2, ts3]
twe_model = sk_kmeans.TimeSeriesKMeans(n_clusters=2, metric="twe")
twe_model.fit(data_df)
```

**Expected behavior**
The model should not throw an error. However, the output is  `ValueError: The data has unequal length series, this clusterer cannot handle unequal length series`

```
System:
    python: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
   machine: Windows-11-10.0.22631-SP0

Python dependencies:
          pip: 24.2
       sktime: 0.32.1
      sklearn: 1.5.1
       skbase: 0.8.2
        numpy: 2.0.1
        scipy: 1.14.0
       pandas: 2.2.2
   matplotlib: 3.9.1
       joblib: 1.4.2
        numba: 0.60.0
  statsmodels: 0.14.2
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: 0.6.3
        torch: None
   tensorflow: None
```
</details>
