### ISSUE TITLE
[BUG] TinyTimeMixer should not create validation set if validation_split is None

### ISSUE THREAD

**Issue by geetu040** [sktime/sktime#7644]
**Describe the bug**

`TinyTimeMixerForecaster` always creates a validation set even if `validation_split is None`, in which case the `temporal_train_test_split` defaults the `validation_split` to `0.25` 

Following fixes should be made:
- create `y_test` only if `validation_split is not None`
- rename data split: `test` to `eval`

**To Reproduce**

```python
from sktime.forecasting.ttm import TinyTimeMixerForecaster
from sktime.datasets import load_airline
y = load_airline()

forecaster = TinyTimeMixerForecaster(
	config={"context_length": 10},
	training_args={
		"output_dir": "test_output",
		"report_to": "none",
	},
	validation_split=None, # defaults validation_split to 0.25
)
forecaster.fit(y, fh=[1, 2, 3])
y_pred = forecaster.predict()
```

**Expected behavior**

when `validation_split is None`, `test` should not be created and not passed to the `Trainer`

**Versions**
<details>

```
System:
    python: 3.12.5 | packaged by Anaconda, Inc. | (main, Sep 12 2024, 18:27:27) [GCC 11.2.0]
executable: /home/geetu/miniconda3/envs/ai/bin/python
   machine: Linux-6.8.0-51-generic-x86_64-with-glibc2.39

Python dependencies:
          pip: 24.2
       sktime: 0.34.0
      sklearn: 1.5.2
       skbase: 0.8.3
        numpy: 1.26.4
        scipy: 1.14.1
       pandas: 2.2.3
   matplotlib: 3.9.2
       joblib: 1.4.2
        numba: None
  statsmodels: None
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: 2.4.1
   tensorflow: 2.18.0
```

</details>
