### ISSUE TITLE
[BUG] HolidayFeatures does not work for panel data anymore

### ISSUE THREAD

**Issue by RobKuebler** [sktime/sktime#8006]
**Describe the bug**
In the past (sktime 0.25.0), I could use the `HolidayTransformer` to create dummies for all holidays that appeared in the date column (last column of the multi index). However, now it only works for time series with a simple time index.

**To Reproduce**
```python
from datetime import date

from holidays import country_holidays
import pandas as pd

from sktime.transformations.series.holiday import HolidayFeatures


index = pd.MultiIndex.from_product([
    [1, 2],
    pd.date_range(start="2024-12-31", periods=3)
])

X = pd.DataFrame(
    data={"A": range(len(index))},
    index=index
)

h = HolidayFeatures(calendar=country_holidays("US"))
h.fit_transform(X)
```

The output is empty, although New Year appears in the time range.

**Expected behavior**
A dataframe with a column "New Year's Day" that is 1 on 2025-01-01.

**Additional context**
It works fine when replacing the multi index with `index = pd.date_range(start="2024-12-31", periods=3)`.
It also works fine when defining `h = HolidayFeatures(calendar={date(2025, 1, 1): "New Year's Day"})` (i.e. not using the holidays library) with panel data. Just the combination of panel data + holidays library doesn't seem to work for some reason.

I found out that it might be because of the lazy nature of the holidays library. If I do this, it works as expected:
```python
cal = country_holidays("US")
"2025-01-01" in cal # initializes the year 2025 in the calendar

h = HolidayFeatures(calendar=cal)
h.fit_transform(X) # this works as intended now
```

**Versions**
Python dependencies:
          pip: 22.3.1
       sktime: 0.36.0
      sklearn: 1.6.1
       skbase: 0.12.0
        numpy: 1.23.5
        scipy: 1.10.0
       pandas: 1.5.3
   matplotlib: 3.7.0
       joblib: 1.2.0
        numba: None
  statsmodels: 0.13.5
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: 2.6.0
   tensorflow: None

holidays: 0.68

**Comment by fkiraly** [comment]
I cannot reproduce the error on current `main`, windows, python 3.12.

My output:

![Image](https://github.com/user-attachments/assets/afa1a27f-be77-4e80-a638-fa46eb127f39)

**Comment by fkiraly** [comment]
other versions - maybe your `pandas` is too old?

```
Python dependencies:
          pip: 24.0
       sktime: 0.36.0
      sklearn: 1.6.1
       skbase: 0.12.0
        numpy: 2.0.1
        scipy: 1.14.0
       pandas: 2.2.2
   matplotlib: 3.9.1
       joblib: 1.4.2
        numba: None
  statsmodels: 0.14.2
     pmdarima: 2.0.4
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: 2.3.1
   tensorflow: None
```

**Comment by Garve** [comment]
Hi!

It still happens with pandas 2.2.2 (the other versions left unchanged). Maybe it also helps that I run it on Databricks. The onl fix that I found is doing this:

```python
cal = country_holidays("US")
"2025-01-01" in cal # initializes the year 2025 in the calendar

h = HolidayFeatures(calendar=cal)
h.fit_transform(X) # this works as intended now
```

Without the line `"2025-01-01" in cal` (or any other line that forces the holidays object to produce actual dates), it doesn't work for me.

**Comment by fnhirwa** [comment]
![Image](https://github.com/user-attachments/assets/1c3d0522-ae68-43c4-bb4a-45d8e248809f)
 Getting  this output from the main branch.

```
System:
    python: 3.12.8 (main, Dec  3 2024, 18:42:41) [Clang 16.0.0 (clang-1600.0.26.4)]
executable: /Users/hirwa/Desktop/open/skt/bin/python
   machine: macOS-15.3.2-arm64-arm-64bit

Python dependencies:
          pip: 24.2
       sktime: 0.33.1
      sklearn: 1.5.2
       skbase: 0.8.3
        numpy: 1.26.4
        scipy: 1.14.1
       pandas: 2.2.3
   matplotlib: 3.9.2
       joblib: 1.4.2
        numba: 0.60.0
  statsmodels: 0.14.4
     pmdarima: 2.0.4
statsforecast: 1.7.8
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
```
