### ISSUE TITLE
[BUG] StatsForecastGarch - cannot import name '_check_estimator_deps' from 'skbase.utils.dependencies'

### ISSUE THREAD

**Issue by Baptiste-ceapc** [sktime/sktime#8043]
**I installed sktime, skbase, and all the extras, but when I run the basic code from the documentation for the GARCH model, it shows me
 from skbase.utils.dependencies import _check_estimator_deps
ImportError: cannot import name '_check_estimator_deps' from 'skbase.utils.dependencies' **

**To Reproduce**

```python
from sktime.datasets import load_airline
from sktime.forecasting.arch import StatsForecastGARCH
from sktime import show_versions; show_versions()
y = load_airline()
forecaster = StatsForecastGARCH(p=2,q=1)
forecaster.fit(y)
y_pred = forecaster.predict(fh=[1,2,3])
```

**Expected behavior**

**Additional context**

**Python dependencies:
          pip: 25.0.1
       sktime: 0.36.0
      sklearn: 1.5.2
       skbase: 0.12.0
        numpy: 1.26.4
        scipy: 1.15.2
       pandas: 2.2.3
   matplotlib: 3.10.1
       joblib: 1.4.2
        numba: 0.61.0
  statsmodels: 0.14.4
     pmdarima: 2.0.4
statsforecast: 2.0.1
      tsfresh: 0.20.3
      tslearn: 0.6.3
        torch: 2.6.0
   tensorflow: 2.16.2**
<details>

</details>

**Comment by yarnabrina** [comment]
Hi @Baptiste-ceapc I could not reproduce the error you described. Can you please share the full traceback?

**Comment by fkiraly** [comment]
I could also not reproduce the error.

```
System:
    python: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]
   machine: Windows-11-10.0.26100-SP0

Python dependencies:
          pip: 24.0
       sktime: 0.36.0
      sklearn: 1.6.1
       skbase: 0.8.1
        numpy: 1.26.4
        scipy: 1.14.0
       pandas: 2.2.2
   matplotlib: 3.9.1
       joblib: 1.4.2
        numba: 0.61.0
  statsmodels: 0.14.2
     pmdarima: 2.0.4
statsforecast: 2.0.1
      tsfresh: None
      tslearn: None
        torch: 2.3.1
   tensorflow: None
```
